# Generated by Django 5.0.4 on 2024-04-06 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="myuser",
            name="First_name",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name="myuser",
            name="city",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name="myuser",
            name="country",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name="myuser",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("MALE", "MALE"), ("FEMALE", "FEMALE"), ("OTHERS", "OTHERS")],
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="myuser",
            name="last_name",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name="myuser",
            name="mobile_number",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="myuser",
            name="state",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
